## Different types of arrays/matrices

In [5]:
import numpy as np

In [7]:
# All zeros matrix
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# All ones matrix
a = np.ones((4,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Any other number matrix with dtype
a = np.full((2,3), 15.3, dtype='float32')
print(a)

[[15.3 15.3 15.3]
 [15.3 15.3 15.3]]


In [17]:
# Using full_like(array, number) to create an matrix of any number with a shape of a predefined matrix
b = np.array([[1,2,3], [8, 9, 10]])
b = np.full_like(b, 9)
print(b)

[[9 9 9]
 [9 9 9]]


In [31]:
# Random decimal number
c = np.random.rand(2,4)
print(c)
c = np.random.random_sample(a.shape)
print(c)

[[0.15417273 0.77540714 0.38530446 0.30060253]
 [0.71436817 0.26993833 0.0758735  0.70317855]]
[[0.49892339 0.0594243  0.65162425]
 [0.69621557 0.05946928 0.50758811]]


In [36]:
# Random integer values
d = np.random.randint(-10, 10, size=(3,4))
print(d)

[[ -5  -8  -7   6]
 [ -2  -8 -10  -9]
 [  1   3  -9   1]]


In [38]:
# Indentity matrix
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
# Repeat arrays
a = np.array([[1, 2, 3]])
r = np.repeat(a, 3, axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
