## Building an array

![problem](https://i.ibb.co/F7pDxj7/Capture.png)

In [2]:
import numpy as np

In [3]:
ans = np.ones((5,5))
print(ans)
z = np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [5]:
ans[1:4, 1:4] = z

In [6]:
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
