## Mathematics

In [2]:
import numpy as np

In [8]:
# Simple mathematical operation
a = np.array([1, 2, 3, 4])
a + 2

array([3, 4, 5, 6])

In [5]:
a * 10

array([10, 20, 30, 40])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [15]:
# Trigonometrical Operation
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [28]:
a = np.ones((2,3))
b = np.full((3,5), 6)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [29]:
c = np.matmul(a, b)
print(c)

[[18. 18. 18. 18. 18.]
 [18. 18. 18. 18. 18.]]


In [31]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [33]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [63]:
stat = np.array([[18, 52, 96], [1, 2, 85]])
np.min(stat, axis=1)

array([18,  1])

In [64]:
np.max(stat)

96

In [68]:
np.sum(stat, axis=0)

array([ 19,  54, 181])