## Boolean masking and Advanced indexing

In [8]:
import numpy as np

In [9]:
# Load from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 1  2 40 87]
 [10 85 96 45]]


In [10]:
filedata > 50

array([[False, False, False,  True],
       [False,  True,  True, False]])

In [18]:
a = filedata[filedata > 50]
print(a)
np.any(filedata > 50, axis=0)

[87 85 96]


array([False,  True,  True,  True])

In [19]:
np.all(filedata > 50, axis=0)

array([False, False, False, False])

In [20]:
(filedata > 50) & (filedata < 90)

array([[False, False, False,  True],
       [False,  True, False, False]])

In [14]:
# Index with a list
a = np.array([1, 50, 100, 500, 600])
a[[1, 3]]

array([ 50, 500])